[tasks.main]
commands = ["docker compose -f ./payment-processor/docker-compose.yml up -d","docker compose build --no-cache","docker compose up -d"]

[tasks.start]
commands = ["npm --prefix api/ start", "npm --prefix worker/ start"]

[tasks.restart]
commands = ["docker compose down", "docker system prune -a --volumes"]

[tasks.test]
commands = ["k6 run rinha-test/rinha.js"]